-- Generated by tools/gen_transit.py — do not edit.
-- Source: AreaTrigger source positions + classic-db areatrigger_teleport destinations.
-- DB2: https://wago.tools/db2 (CSV build 1.60.1.70205).
-- DB: https://github.com/cmangos/classic-db/tree/22b51464f1625f6ef6275771de1f5466c6f5d19e
---@type string, SPFNamespace
local _, ns = ...

-- Loading-screen allowance: 5 s. Only these public transitions are included.
-- Excludes GM/test 1103/1104 and dungeon/raid triggers (Blizzard's own map shows those entrances).
-- Excludes Stormwind's Wizard's Sanctum 702/704: a hop up and down one tower, 12 yd apart on the map,
-- that never shortens a flat route and would stack two pins. Also the unused vault 107/109 (map 35), the
-- Leap of Faith fall 943, and PvP barracks 2527-2534, which have no AreaTrigger in this build.
-- Skyborne Dalaran <-> Stormwind omitted: eligibility is documented, exact endpoints are not sourced.
-- https://benjamh681.github.io/wow-forever-atlas/guide.html (Alliance Skyborne only).

-- stylua: ignore
ns.Portals = {
	-- Source: AreaTrigger 527 -> classic-db areatrigger_teleport 527.
	{
		name = "Portal to Rut'theran Village",
		kind = "portal",
		from = { map = 1, x = 9947.48, y = 2630.04, z = 1318.6 },
		to = { map = 1, x = 8785.79, y = 966.983, z = 30.2 },
		seconds = 5,
	},
	-- Source: AreaTrigger 542 -> classic-db areatrigger_teleport 542.
	{
		name = "Portal to Darnassus",
		kind = "portal",
		from = { map = 1, x = 8799.41, y = 969.787, z = 30.241 },
		to = { map = 1, x = 9946.25, y = 2612.97, z = 1316.49 },
		seconds = 5,
	},
	-- Source: AreaTrigger 2166 -> classic-db areatrigger_teleport 2166.
	{
		name = "Passage to Ironforge",
		kind = "passage",
		from = { map = 369, x = 76.027, y = 10.504, z = -4.297 },
		to = { map = 0, x = -4839.51, y = -1317.74, z = 501.868 },
		seconds = 5,
	},
	-- Source: AreaTrigger 2171 -> classic-db areatrigger_teleport 2171.
	{
		name = "Passage to Stormwind",
		kind = "passage",
		from = { map = 369, x = 80.163, y = 2490.88, z = -1.857 },
		to = { map = 0, x = -8354.23, y = 524.068, z = 91.797 },
		seconds = 5,
	},
	-- Source: AreaTrigger 2173 -> classic-db areatrigger_teleport 2173.
	{
		name = "Passage to Deeprun Tram (Stormwind)",
		kind = "passage",
		from = { map = 0, x = -8346.46, y = 514.031, z = 96.599 },
		to = { map = 369, x = 67.761, y = 2490.98, z = -4.296 },
		seconds = 5,
	},
	-- Source: AreaTrigger 2175 -> classic-db areatrigger_teleport 2175.
	{
		name = "Passage to Deeprun Tram (Ironforge)",
		kind = "passage",
		from = { map = 0, x = -4840.26, y = -1330.46, z = 508.172 },
		to = { map = 369, x = 69.228, y = 10.393, z = -4.297 },
		seconds = 5,
	},
}
