-- Generated by tools/gen_transit.py — do not edit.
-- Source: SpellEffect TELEPORT_UNITS + classic-db spell_target_position destinations.
-- DB2: https://wago.tools/db2 (CSV build 1.60.1.70338).
-- DB: https://github.com/cmangos/classic-db/tree/22b51464f1625f6ef6275771de1f5466c6f5d19e
---@type string, SPFNamespace
local _, ns = ...

-- Class teleports, and items that take you to your bind point. cast: ms; reagents: [item] = count;
-- bind: lands where you bound, which the client only reports by name; to: a world point (yards).
-- No sourced destination on a continent with walking maps: Teleport: Dalaran (1297659).

-- stylua: ignore
ns.Teleports = {
	-- Astral Recall
	{ spell = 556, bind = true, cast = 10000 },
	-- Teleport: Stormwind
	{
		spell = 3561,
		to = { map = 0, x = -9003.46, y = 870.031, z = 29.621 },
		cast = 10000,
		reagents = { [17031] = 1 },
	},
	-- Teleport: Ironforge
	{
		spell = 3562,
		to = { map = 0, x = -4613.62, y = -915.38, z = 501.062 },
		cast = 10000,
		reagents = { [17031] = 1 },
	},
	-- Teleport: Undercity
	{
		spell = 3563,
		to = { map = 0, x = 1773.47, y = 61.121, z = -46.321 },
		cast = 10000,
		reagents = { [17031] = 1 },
	},
	-- Teleport: Darnassus
	{
		spell = 3565,
		to = { map = 1, x = 9664.14, y = 2526.36, z = 1334.27 },
		cast = 10000,
		reagents = { [17031] = 1 },
	},
	-- Teleport: Thunder Bluff
	{
		spell = 3566,
		to = { map = 1, x = -964.98, y = 283.433, z = 111.187 },
		cast = 10000,
		reagents = { [17031] = 1 },
	},
	-- Teleport: Orgrimmar
	{
		spell = 3567,
		to = { map = 1, x = 1469.85, y = -4221.52, z = 58.994 },
		cast = 10000,
		reagents = { [17031] = 1 },
	},
	-- Hearthstone
	{ spell = 8690, item = 6948, bind = true, cast = 10000 },
	-- Teleport: Moonglade
	{ spell = 18960, to = { map = 1, x = 7991.88, y = -2679.84, z = 512.1 }, cast = 10000 },
}
