-- Walking costs between every pair of fixed places the planner routes through (docks, flight masters, portal
-- ends, class teleports' landings), searched once here rather than guessed as straight lines and measured in game.
-- Run from the repo root after rebaking a walking map or changing the places:
-- luajit tools/bake_walks.lua > Data/Walks.lua
local ns = {}
for _, file in ipairs({
	"Data/Routes.lua",
	"Data/Transports.lua",
	"Data/Taxi.lua",
	"Data/Portals.lua",
	"Data/Teleports.lua",
	"Routing/PathGrid.lua",
	"Routing/Path.lua",
	"Routing/PathJobs.lua",
	"Routing/Planner.lua",
}) do
	assert(loadfile(file))("ShortestPathForever", ns)
end
for _, map in ipairs({ 0, 1, 2991 }) do
	assert(loadfile("tools/load_nav.lua"))(map)
end
local Path = ns.Path

local places = {}
local function Add(key, point)
	places[point.map] = places[point.map] or {}
	table.insert(places[point.map], { key = key, point = point })
end
for id, dock in pairs(ns.Docks) do
	Add("dock" .. id, dock)
end
for id, node in pairs(ns.TaxiNodes) do
	Add("taxi" .. id, node)
end
for id, portal in ipairs(ns.Portals) do
	Add("portal" .. (id * 2 - 1), portal.from)
	Add("portal" .. id * 2, portal.to)
end
-- Where a class teleport lands; the bind point moves, so Journey measures its walks in game.
for _, teleport in ipairs(ns.Teleports) do
	if teleport.to then
		Add("teleport" .. teleport.spell, teleport.to)
	end
end

local maps = {}
for map in pairs(places) do
	if Path.HasData(map) then
		maps[#maps + 1] = map
	end
end
table.sort(maps)
print("-- Generated by tools/bake_walks.lua — do not edit.")
print("---@type string, SPFNamespace")
print("local _, ns = ...")
print("")
print("-- Fixed place coordinates rounded to yards, so tests can detect stale walking costs.")
print("ns.WalkPlaces = {")
for _, map in ipairs(maps) do
	local list = places[map]
	table.sort(list, function(a, b)
		return a.key < b.key
	end)
	print(("\t[%d] = {"):format(map))
	for _, place in ipairs(list) do
		print(
			("\t\t%s = { %d, %d },"):format(place.key, math.floor(place.point.x + 0.5), math.floor(place.point.y + 0.5))
		)
	end
	print("\t},")
end
print("}")
print("")
print("-- Running yards between fixed places, { dry, water walking }, false where")
print("-- there is no way through. Sorted keys; optional third/fourth values give reverse costs when they differ.")
print("ns.Walks = {")
for _, map in ipairs(maps) do
	local list = places[map]
	io.stderr:write(("map %d: %d places\n"):format(map, #list))
	print(("\t[%d] = {"):format(map))
	local points, costs = {}, {}
	for i, place in ipairs(list) do
		points[i] = place.point
	end
	for i, point in ipairs(points) do
		costs[i] = { Path.FindManySync(map, point, points), Path.FindManySync(map, point, points, true) }
	end
	local function rounded(cost)
		return cost and math.floor(cost + 0.5) or "false"
	end
	for i = 1, #list do
		for j = i + 1, #list do
			local a, b = list[i], list[j]
			if ns.Planner.Landmass(a.point, ns.Landmasses) == ns.Planner.Landmass(b.point, ns.Landmasses) then
				local dry, wet = rounded(costs[i][1][j]), rounded(costs[i][2][j])
				local backDry, backWet = rounded(costs[j][1][i]), rounded(costs[j][2][i])
				local reverse = (dry ~= backDry or wet ~= backWet) and (", " .. backDry .. ", " .. backWet) or ""
				print(('\t\t["%s %s"] = { %s, %s%s },'):format(a.key, b.key, dry, wet, reverse))
			end
		end
	end
	print("\t},")
end
print("}")
