#!/usr/bin/env python3
"""Pack walking maps into LuaLS-sized files without needing the original mmtile bake."""

import argparse
import re
from pathlib import Path

ENTRY = re.compile(r'\t\t\[(\d+)\] = \{\n((?:\t\t\t"[A-Za-z0-9+/]*",\n)+)\t\t\},')
SECTION = re.compile(r"^\t(\w+) = \{\n(.*?)^\t\},\n", re.MULTILINE | re.DOTALL)
PART_HEADER = "-- Generated by tools/pack_nav.py; loaded after the base map by its TOC.\n"
PART_TYPE = "---@type string[]\n-- stylua: ignore\n"
# LuaLS refuses files over 10 MiB even when preloadFileSize is larger.
MAX_BYTES = 8 * 1024 * 1024


def pack(source):
    return ENTRY.sub(lambda m: f'\t\t[{m[1]}] = "' + "".join(re.findall(r'"([^"]*)"', m[2])) + '",', source)


def split(source, map_id, limit=MAX_BYTES):
    parts = {}
    for section in reversed(list(SECTION.finditer(source))):
        if len(source.encode()) <= limit:
            break
        field, entries = section.groups()
        part = PART_HEADER + PART_TYPE + f"ShortestPathForeverPathData[{map_id}].{field} = {{\n{entries}}}\n"
        if len(part.encode()) > limit:
            raise ValueError(f"Map {map_id} field {field} needs splitting below {limit} bytes")
        parts[field] = part
        source = source[: section.start()] + f"\t{field} = {{}},\n" + source[section.end() :]
    if len(source.encode()) > limit:
        raise ValueError(f"Map {map_id} base exceeds {limit} bytes")
    return source, parts


def write_map(path, limit=MAX_BYTES):
    map_id = int(re.fullmatch(r"Nav(\d+)\.lua", path.name)[1])
    toc = path.with_name(f"ShortestPathForever_Nav{map_id}.toc")
    source = path.read_text()
    previous = []
    for part in sorted(path.parent.glob(f"{path.stem}_*.lua")):
        content = part.read_text()
        if not content.startswith(PART_HEADER):
            raise ValueError(f"Refusing to overwrite an unrecognized generated part: {part}")
        field = part.stem.removeprefix(path.stem + "_")
        prefix = PART_HEADER + PART_TYPE + f"ShortestPathForeverPathData[{map_id}].{field} = {{\n"
        if not content.startswith(prefix) or not content.endswith("}\n"):
            raise ValueError(f"Malformed generated part: {part}")
        # Repacking an already split map must be identical to packing the original bake.
        source = source.replace(f"\t{field} = {{}},\n", f"\t{field} = {{\n{content[len(prefix) : -2]}\t}},\n")
        previous.append(part)
    declaration = f"-- stylua: ignore\nShortestPathForeverPathData[{map_id}] = {{"
    typed = "---@type SPFNavData\n" + declaration
    if typed not in source:
        source = source.replace(declaration, typed)
    result, parts = split(pack(source), map_id, limit)
    names = [path.name, *(f"{path.stem}_{field}.lua" for field in sorted(parts))]
    lines = [line for line in toc.read_text().splitlines() if line not in {path.name, *(p.name for p in previous)}]
    path.write_text(result)
    for field, content in parts.items():
        path.with_name(f"{path.stem}_{field}.lua").write_text(content)
    for part in previous:
        if part.name not in names:
            part.unlink()
    toc.write_text("\n".join([*lines, *names]) + "\n")
    print(f"{path}: {len(source.encode())} bytes -> {len(names)} file(s)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("files", nargs="*", type=Path)
    args = parser.parse_args()
    base = re.compile(r"Nav\d+\.lua")
    for path in args.files:
        if not base.fullmatch(path.name):
            parser.error(f"{path} is not a base walking map (NavN.lua); pass the base map to repack its parts")
    maps = sorted(Path(".").glob("ShortestPathForever_Nav*/Nav*.lua"))
    for path in args.files or [path for path in maps if base.fullmatch(path.name)]:
        write_map(path)
