#!/usr/bin/env python3
"""Pack walking maps into LuaLS-sized files without needing the original mmtile bake."""

import argparse
import re
from pathlib import Path

try:
    from tools.forever_tools.fsio import atomic_write, publish
except ModuleNotFoundError:
    from forever_tools.fsio import atomic_write, publish

ENTRY = re.compile(r'\t\t\[(\d+)\] = \{\n((?:\t\t\t"[A-Za-z0-9+/]*",\n)+)\t\t\},')
SECTION = re.compile(r"^\t(\w+) = \{\n(.*?)^\t\},\n", re.MULTILINE | re.DOTALL)
PART_HEADER = "-- Generated by tools/pack_nav.py; loaded after the base map by its TOC.\n"
PART_TYPE = "---@type string[]\n-- stylua: ignore\n"


def part_prefix(map_id, field):
    return PART_HEADER + PART_TYPE + f"ShortestPathForeverPathData[{map_id}].{field} = {{\n"


def pack(source):
    return ENTRY.sub(lambda m: f'\t\t[{m[1]}] = "' + "".join(re.findall(r'"([^"]*)"', m[2])) + '",', source)


PART_BYTES = 512 * 1024
FIELDS = ("graph", "grid", "height", "floor")
CELL_ENTRY = re.compile(r'\t\t\[(\d+)\] = "([A-Za-z0-9+/]*)",')
PART_ENTRY = re.compile(r'data\.(graph|grid|height|floor)\[(\d+)\] = "([A-Za-z0-9+/]*)"')
CHUNK_HEADER = "-- Generated by tools/pack_nav.py; navigation clusters loaded on demand.\n"


def read_map(path, map_id):
    source = path.read_text()
    previous = []
    for part in sorted(path.parent.glob(f"{path.stem}_*.lua")):
        content = part.read_text()
        field = part.stem.removeprefix(path.stem + "_")
        prefix = part_prefix(map_id, field)
        if not content.startswith(prefix) or not content.endswith("}\n"):
            raise ValueError(f"Unrecognized navigation part: {part}")
        source = source.replace(f"\t{field} = {{}},\n", f"\t{field} = {{\n{content[len(prefix) : -2]}\t}},\n")
        previous.append(part)
    source = pack(source)
    fields = {field: {} for field in FIELDS}
    for section in SECTION.finditer(source):
        field, entries = section.groups()
        if field in fields:
            for match in CELL_ENTRY.finditer(entries):
                fields[field][int(match[1])] = match[2]
    manifests = [m[2] for m in SECTION.finditer(source) if m[1] == "parts"]
    manifest = dict((int(k), int(v)) for k, v in re.findall(r"\[(\d+)\] = (\d+),", "".join(manifests)))
    children = sorted(path.parent.parent.glob(f"ShortestPathForever_Nav{map_id}_*"))
    if manifests:
        expected = {f"ShortestPathForever_Nav{map_id}_{part}" for part in manifest.values()}
        if expected != {child.name for child in children}:
            raise ValueError(f"Navigation part inventory disagrees with map {map_id} manifest")
    elif children:
        raise ValueError(f"Navigation addons exist without a map {map_id} manifest")
    for child in children:
        if {p.name for p in child.iterdir()} != {"Data.lua", f"{child.name}.toc"}:
            raise ValueError(f"Unrecognized files in navigation addon: {child}")
        part = child / "Data.lua"
        if not part.is_file() or not part.read_text().startswith(CHUNK_HEADER):
            raise ValueError(f"Unrecognized navigation addon: {child}")
        part_id = int(child.name.rsplit("_", 1)[1])
        keys = set()
        content = part.read_text()
        if f"data.loadedParts[{part_id}] = true" not in content:
            raise ValueError(f"Missing navigation completion marker: {part}")
        for match in PART_ENTRY.finditer(content):
            field, key, value = match.groups()
            key = int(key)
            if key in fields[field]:
                raise ValueError(f"Duplicate navigation entry: {field}[{key}]")
            if manifest.get(key) != part_id:
                raise ValueError(f"Navigation entry {key} is in the wrong addon: {child}")
            keys.add(key)
            fields[field][key] = value
        if keys != {key for key, value in manifest.items() if value == part_id}:
            raise ValueError(f"Navigation part is missing manifest entries: {part}")
    for field in ("graph", "grid", "height"):
        if manifests and set(fields[field]) != set(manifest):
            raise ValueError(f"Navigation {field} inventory disagrees with map {map_id} manifest")
    return source, fields, previous, children


def partition(fields, map_id, limit):
    groups, current, size = [], [], 0
    for key in sorted(set().union(*(values.keys() for values in fields.values()))):
        lines = [f'data.{field}[{key}] = "{fields[field][key]}"\n' for field in FIELDS if key in fields[field]]
        entry = "".join(lines)
        # Leave space for the header, namespace declaration and completion marker.
        if len(entry.encode()) + 256 > limit:
            raise ValueError(f"Map {map_id} cluster {key} exceeds the navigation part limit")
        if current and size + len(entry.encode()) + 256 > limit:
            groups.append(current)
            current, size = [], 0
        current.append((key, entry))
        size += len(entry.encode())
    if current:
        groups.append(current)
    return groups


def write_map(path, limit=PART_BYTES):
    map_id = int(re.fullmatch(r"Nav(\d+)\.lua", path.name)[1])
    toc = path.with_name(f"ShortestPathForever_Nav{map_id}.toc")
    source, fields, previous, children = read_map(path, map_id)
    groups = partition(fields, map_id, limit)
    root = SECTION.sub(lambda m: f"\t{m[1]} = {{}},\n" if m[1] in FIELDS else "", source)
    root = re.sub(r"^\tloadedParts = \{\},\n", "", root, flags=re.MULTILINE)
    # A base addon holds only map metadata and the cluster-to-addon manifest.
    manifest = (
        "\tparts = {\n"
        + "".join(f"\t\t[{key}] = {index},\n" for index, group in enumerate(groups, 1) for key, _ in group)
        + "\t},\n\tloadedParts = {},\n"
    )
    root = root.rstrip()[:-1] + manifest + "}\n"
    declaration = f"-- stylua: ignore\nShortestPathForeverPathData[{map_id}] = {{"
    if "---@type SPFNavData\n" + declaration not in root:
        root = root.replace(declaration, "---@type SPFNavData\n" + declaration)
    outputs = {path: root}
    names = []
    parent_name = f"ShortestPathForever_Nav{map_id}"
    for index, group in enumerate(groups, 1):
        name = f"{parent_name}_{index}"
        names.append(name)
        directory = path.parent.parent / name
        data = CHUNK_HEADER + f"---@type SPFNavData\nlocal data = ShortestPathForeverPathData[{map_id}]\n"
        data += "-- stylua: ignore start\n" + "".join(entry for _, entry in group)
        data += f"data.loadedParts[{index}] = true\n-- stylua: ignore end\n"
        if len(data.encode()) > limit:
            raise ValueError(f"Navigation addon {name} exceeds {limit} bytes")
        outputs[directory / "Data.lua"] = data
        outputs[directory / f"{name}.toc"] = (
            f"## Interface: 16001\n## Title: Shortest Path Forever - Walking map {map_id}, part {index}\n"
            f"## Notes: Walking terrain loaded when a route needs it.\n## LoadOnDemand: 1\n"
            f"## Dependencies: {parent_name}\n## X-License: GPL-3.0-or-later\n"
            "## IconTexture: Interface\\AddOns\\ShortestPathForever\\media\\Icon\n\nData.lua\n"
        )
    lines = [line for line in toc.read_text().splitlines() if not line.strip().endswith(".lua")]
    outputs[toc] = "\n".join([*lines, path.name]) + "\n"
    publish(outputs)
    for old in previous:
        old.unlink()
    for child in children:
        for old in (child / "Data.lua", child / f"{child.name}.toc"):
            if old not in outputs:
                old.unlink()
        if child.name not in names:
            child.rmdir()
    print(f"{path}: {len(fields['grid'])} clusters in {len(groups)} bounded load-on-demand addons")


def update_package(root):
    package = root / ".pkgmeta"
    if not package.is_file():
        return
    source = package.read_text()
    source = re.sub(r"^  ShortestPathForever/ShortestPathForever_Nav\d+(?:_\d+)?:.*\n", "", source, flags=re.MULTILINE)
    directories = sorted(root.glob("ShortestPathForever_Nav*"))
    entries = "".join(f"  ShortestPathForever/{p.name}: {p.name}\n" for p in directories if p.is_dir())
    source = source.replace("move-folders:\n", "move-folders:\n" + entries)
    atomic_write(package, source)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("files", nargs="*", type=Path)
    args = parser.parse_args()
    base = re.compile(r"Nav\d+\.lua")
    for path in args.files:
        if not base.fullmatch(path.name):
            parser.error(f"{path} is not a base walking map (NavN.lua); pass the base map to repack its parts")
    maps = sorted(Path(".").glob("ShortestPathForever_Nav*/Nav*.lua"))
    for path in args.files or [path for path in maps if base.fullmatch(path.name)]:
        write_map(path)

    if not args.files:
        update_package(Path.cwd())
