#!/usr/bin/env python3
"""Bundle compressed walking maps inside the main addon."""

import argparse
import base64
import re
import zlib
from pathlib import Path

try:
    from tools.forever_tools.fsio import atomic_write, publish
except ModuleNotFoundError:
    from forever_tools.fsio import atomic_write, publish

ENTRY = re.compile(r'\t\t\[(\d+)\] = \{\n((?:\t\t\t"[A-Za-z0-9+/]*",\n)+)\t\t\},')
SECTION = re.compile(r"^\t(\w+) = \{\n(.*?)^\t\},\n", re.MULTILINE | re.DOTALL)
PART_HEADER = "-- Generated by tools/pack_nav.py; loaded after the base map by its TOC.\n"
PART_TYPE = "---@type string[]\n-- stylua: ignore\n"


def part_prefix(map_id, field):
    return PART_HEADER + PART_TYPE + f"ShortestPathForeverPathData[{map_id}].{field} = {{\n"


def pack(source):
    return ENTRY.sub(lambda m: f'\t\t[{m[1]}] = "' + "".join(re.findall(r'"([^"]*)"', m[2])) + '",', source)


PART_BYTES = 512 * 1024
FIELDS = ("graph", "grid", "height", "floor")
CELL_ENTRY = re.compile(r'\t\t\[(\d+)\] = "([A-Za-z0-9+/]*)",')
PART_ENTRY = re.compile(r'data\.(graph|grid|height|floor)\[(\d+)\] = "([A-Za-z0-9+/]*)"')
CHUNK_HEADER = "-- Generated by tools/pack_nav.py; navigation clusters loaded on demand.\n"


def read_map(path, map_id):
    source = path.read_text()
    previous = []
    for part in sorted(path.parent.glob(f"{path.stem}_*.lua")):
        content = part.read_text()
        field = part.stem.removeprefix(path.stem + "_")
        prefix = part_prefix(map_id, field)
        if not content.startswith(prefix) or not content.endswith("}\n"):
            raise ValueError(f"Unrecognized navigation part: {part}")
        source = source.replace(f"\t{field} = {{}},\n", f"\t{field} = {{\n{content[len(prefix) : -2]}\t}},\n")
        previous.append(part)
    source = pack(source)
    fields = {field: {} for field in FIELDS}
    for section in SECTION.finditer(source):
        field, entries = section.groups()
        if field in fields:
            for match in CELL_ENTRY.finditer(entries):
                fields[field][int(match[1])] = match[2]
    manifests = [m[2] for m in SECTION.finditer(source) if m[1] == "parts"]
    manifest = dict((int(k), int(v)) for k, v in re.findall(r"\[(\d+)\] = (\d+),", "".join(manifests)))
    children = sorted(path.parent.parent.glob(f"ShortestPathForever_Nav{map_id}_*"))
    if manifests:
        expected = {f"ShortestPathForever_Nav{map_id}_{part}" for part in manifest.values()}
        if expected != {child.name for child in children}:
            raise ValueError(f"Navigation part inventory disagrees with map {map_id} manifest")
    elif children:
        raise ValueError(f"Navigation addons exist without a map {map_id} manifest")
    for child in children:
        if {p.name for p in child.iterdir()} != {"Data.lua", f"{child.name}.toc"}:
            raise ValueError(f"Unrecognized files in navigation addon: {child}")
        part = child / "Data.lua"
        if not part.is_file() or not part.read_text().startswith(CHUNK_HEADER):
            raise ValueError(f"Unrecognized navigation addon: {child}")
        part_id = int(child.name.rsplit("_", 1)[1])
        keys = set()
        content = part.read_text()
        if f"data.loadedParts[{part_id}] = true" not in content:
            raise ValueError(f"Missing navigation completion marker: {part}")
        for match in PART_ENTRY.finditer(content):
            field, key, value = match.groups()
            key = int(key)
            if key in fields[field]:
                raise ValueError(f"Duplicate navigation entry: {field}[{key}]")
            if manifest.get(key) != part_id:
                raise ValueError(f"Navigation entry {key} is in the wrong addon: {child}")
            keys.add(key)
            fields[field][key] = value
        if keys != {key for key, value in manifest.items() if value == part_id}:
            raise ValueError(f"Navigation part is missing manifest entries: {part}")
    for field in ("graph", "grid", "height"):
        if manifests and set(fields[field]) != set(manifest):
            raise ValueError(f"Navigation {field} inventory disagrees with map {map_id} manifest")
    return source, fields, previous, children


BLOCK_BYTES = 16 * 1024
PACKED_ENTRY = re.compile(r"data\.packed\.(graph|grid|height|floor)\[(\d+)\] = \{([^}]+)\}")


def read_packed(path, map_id):
    source = path.read_text()
    fields = {field: {} for field in FIELDS}
    for part in sorted(path.parent.glob(f"Nav{map_id}_*.lua")):
        content = part.read_text()
        if not content.startswith(PACKED_HEADER):
            raise ValueError(f"Unrecognized navigation part: {part}")
        for field, key, blocks in PACKED_ENTRY.findall(content):
            key = int(key)
            if key in fields[field]:
                raise ValueError(f"Duplicate navigation entry: {field}[{key}]")
            values = re.findall(r'"([A-Za-z0-9+/=]+)"', blocks)
            fields[field][key] = "".join(
                zlib.decompress(base64.b64decode(value, validate=True)).decode("ascii") for value in values
            )
    counts = dict((field, int(count)) for field, count in re.findall(r"(graph|grid|height|floor) = (\d+)", source))
    if counts != {field: len(entries) for field, entries in fields.items()}:
        raise ValueError(f"Compressed navigation inventory disagrees with map {map_id} metadata")
    return source, fields, [], []


PACKED_HEADER = "-- Generated by tools/pack_nav.py; compressed terrain for on-demand decoding.\n"


def write_bundle(root, sources, limit=PART_BYTES):
    # Validate every source before publishing or deleting the previous layout.
    sources = list(sources)
    selected = {int(re.fullmatch(r"Nav(\d+)\.lua", path.name)[1]) for path in sources}
    for existing in sorted((root / "Nav").glob("Nav*.lua")):
        match = re.fullmatch(r"Nav(\d+)\.lua", existing.name)
        if match and int(match[1]) not in selected:
            sources.append(existing)
    sources.sort(key=lambda path: int(re.fullmatch(r"Nav(\d+)\.lua", path.name)[1]))
    loaded = []
    for path in sources:
        map_id = int(re.fullmatch(r"Nav(\d+)\.lua", path.name)[1])
        reader = read_packed if path.parent.name == "Nav" else read_map
        loaded.append((map_id, path, *reader(path, map_id)))
    outputs, obsolete = {}, []
    directory = root / "Nav"
    files = []
    for map_id, path, source, fields, previous, children in loaded:
        metadata = SECTION.sub(lambda m: f"\t{m[1]} = {{}},\n" if m[1] in FIELDS else "", source)
        metadata = re.sub(r"^\t(?:loadedParts|packed|counts) = .*\n", "", metadata, flags=re.MULTILINE)
        counts = ", ".join(f"{field} = {len(fields[field])}" for field in FIELDS)
        metadata = (
            metadata.rstrip()[:-1]
            + f"\tcounts = {{ {counts} }},\n"
            + "\tpacked = { graph = {}, grid = {}, height = {}, floor = {} },\n}\n"
        )
        declaration = f"-- stylua: ignore\nShortestPathForeverPathData[{map_id}] = {{"
        if "---@type SPFNavData\n" + declaration not in metadata:
            metadata = metadata.replace(declaration, "---@type SPFNavData\n" + declaration)
        target = directory / path.name
        outputs[target] = metadata
        files.append(target.name)
        header = (
            PACKED_HEADER
            + f"---@type SPFNavData\nlocal data = ShortestPathForeverPathData[{map_id}]\n-- stylua: ignore start\n"
        )
        part, content = 1, header
        for key in sorted(set().union(*(values.keys() for values in fields.values()))):
            for field in FIELDS:
                if key not in fields[field]:
                    continue
                raw = fields[field][key].encode("ascii")
                blocks = [
                    base64.b64encode(zlib.compress(raw[offset : offset + BLOCK_BYTES], 9)).decode("ascii")
                    for offset in range(0, len(raw), BLOCK_BYTES)
                ]
                if not blocks:
                    blocks = [base64.b64encode(zlib.compress(b"", 9)).decode("ascii")]
                line = f"data.packed.{field}[{key}] = {{" + ", ".join(f'"{block}"' for block in blocks) + "}\n"
                if len((header + line).encode()) + 32 > limit:
                    raise ValueError(f"Map {map_id} cluster {key} exceeds the navigation file limit")
                if len((content + line).encode()) + 32 > limit:
                    name = f"Nav{map_id}_{part}.lua"
                    outputs[directory / name] = content + "-- stylua: ignore end\n"
                    files.append(name)
                    part, content = part + 1, header
                content += line
        name = f"Nav{map_id}_{part}.lua"
        outputs[directory / name] = content + "-- stylua: ignore end\n"
        files.append(name)
        if path.parent.name.startswith("ShortestPathForever_Nav"):
            obsolete.extend([path, path.with_name(f"ShortestPathForever_Nav{map_id}.toc"), *previous])
            for child in children:
                obsolete.extend([child / "Data.lua", child / f"{child.name}.toc"])
    outputs[directory / "Nav.xml"] = (
        '<Ui xmlns="http://www.blizzard.com/wow/ui/">\n'
        + "".join(f'\t<Script file="{file}"/>\n' for file in files)
        + "</Ui>\n"
    )
    map_ids = {entry[0] for entry in loaded}
    for old in directory.glob("Nav*.lua"):
        match = re.fullmatch(r"Nav(\d+)(?:_\d+)?\.lua", old.name)
        if not match or int(match[1]) not in map_ids:
            raise ValueError(f"Unrecognized navigation file: {old}")
        if old not in outputs:
            if not old.read_text().startswith(PACKED_HEADER):
                raise ValueError(f"Unrecognized navigation file: {old}")
            obsolete.append(old)
    publish(outputs)
    for old in obsolete:
        if old.exists():
            old.unlink()
    for _, path, _, _, _, children in loaded:
        for child in children:
            child.rmdir()
        if path.parent.name.startswith("ShortestPathForever_Nav"):
            path.parent.rmdir()
    update_package(root)
    print(f"{directory}: {len(loaded)} maps in one addon, {len(files)} compressed Lua files")


def update_package(root):
    package = root / ".pkgmeta"
    if package.is_file():
        source = package.read_text()
        source = re.sub(
            r"# The walking maps.*\nmove-folders:\n(?:  ShortestPathForever/ShortestPathForever_Nav[^\n]+\n)+\n",
            "",
            source,
        )
        atomic_write(package, source)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("files", nargs="*", type=Path)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    base = re.compile(r"Nav\d+\.lua")
    for path in args.files:
        if not base.fullmatch(path.name):
            parser.error(f"{path} is not a base walking map (NavN.lua); pass the base map to repack its parts")
    sources = (
        args.files
        or sorted(args.root.glob("Nav/Nav*.lua"))
        or sorted(args.root.glob("ShortestPathForever_Nav*/Nav*.lua"))
    )
    write_bundle(args.root, [path for path in sources if base.fullmatch(path.name)])
