-- Generated by tools/baker/gen_nav.py — do not edit.
-- Source: own bake of the World of Warcraft client (wow_classic_beta), Mappster/DotRecast.
-- Map 2991 (Zephras Isle), mmtile rows 23-29 x cols 26-31.
-- UnitPosition's frame (x north, y west). Cluster k (0-based) is the ADT tile x in [(cx0 + k // ny) T, +T),
-- y in [(cy0 + k % ny) T, +T), T = 1600 / 3, cut into cells x cells cells, x-major. Base64 (A-Za-z0-9+/).
-- graph[k + 1]: n(2) | n x [cell(3) layer(1) component(2) degree(1)] | edges in node order [cluster offset(1):
--   (dx + 1) * 3 + dy + 1, node(2), cost(2) swimming with water at swim, cost(2) walking on water, both in
--   running yards]. grid[k + 1]: per cell value * 16 + flags, where value 0 blocked, 1 ground, 2 water;
--   flags 1/2 close the step to the +x/+y neighbour, 4/8 open the +x+y/+x-y
--   diagonal (otherwise a diagonal is open when either L-shaped detour is). A symbol >= 48 repeats the
--   previous cell (symbol - 47) more times. Nodes are local cells, then floors from cells * cells on.
-- height[k + 1]: base heights of the walkable cells in cell order, in zstep yards, each against its -y
--   neighbour (else its -x neighbour, else the previous cell): symbols 0-46 add -23..23, 47 is followed by
--   an absolute value + 2048 (2), a symbol >= 48 repeats the previous difference (symbol - 47) more times.
-- floor[k + 1]: surfaces above or below the base one, numbered from cells * cells in order.
--   n(3) | n x [cell(3) count(1) count x [value(1) height + 2048(2) steps(2)]] | m(3) | m x [node(3) direction(1)
--   layer(1)]. A floor's steps bit d links it to the surface in direction d nearest its height; the m links are
--   the rest: a floor's links to another surface, and a base cell's links to floors across the cluster border
--   (inside the cluster they are the reverse of the floors' own). Layer 0 is the base surface, i the cell's ith
--   floor from the bottom; directions 0-7 are +x, -x, +y, -y, +x+y, +x-y, -x+y, -x-y.
ShortestPathForeverPathData = ShortestPathForeverPathData or {}

---@type SPFNavData
-- stylua: ignore
ShortestPathForeverPathData[2991] = {
	cx0 = 2,
	cy0 = 0,
	nx = 7,
	ny = 6,
	cells = 67,
	swim = 3.000000,
	zstep = 2,
	graph = {},
	grid = {},
	height = {},
	floor = {},
	counts = { graph = 24, grid = 24, height = 24, floor = 24 },
	packed = { graph = {}, grid = {}, height = {}, floor = {} },
}
